"""
Django settings for transs_flow project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*dl&t7!4eu%antq@qp!*t$#h4&8#rinibme#@29budotu5zfgu'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'core',
    'factories.assembly.departments.qa.ipqc',
    'factories.assembly.departments.qa',
    'factories.assembly.departments',
    'factories.assembly',
    'factories',
    
    'widget_tweaks',
    'frontend',
    'rest_framework',
    'rest_framework.authtoken',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'transs_flow.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],  # Add your templates folder here
        "APP_DIRS": True,  # This still keeps app templates discoverable
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = 'transs_flow.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# ---------------------- MYSQL (Aiven) ----------------------
MYSQL_HOST = "mysql-rty-rty.d.aivencloud.com"
MYSQL_PORT = 16775
MYSQL_USER = "avnadmin"
MYSQL_PASSWORD = "AVNS_COcv7nfPnntH_BeZ84u"
MYSQL_DB = "transs_flow_final"
MYSQL_DB_MODEL = "defaultdb"
MYSQL_DB_CHAT = "chatdb"
MYSQL_CA = os.path.join(BASE_DIR, "certs", "aiven-ca.pem")

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': MYSQL_DB,
        'USER': MYSQL_USER,
        'PASSWORD': MYSQL_PASSWORD,
        'HOST': MYSQL_HOST,
        'PORT': MYSQL_PORT,
        'OPTIONS': {
            'ssl': {
                'ca': MYSQL_CA,
            },
        },
    },
    
    'defaultdb': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': MYSQL_DB_MODEL,
        'USER': MYSQL_USER,
        'PASSWORD': MYSQL_PASSWORD,
        'HOST': MYSQL_HOST,
        'PORT': MYSQL_PORT,
        'OPTIONS': {
            'ssl': {
                'ca': MYSQL_CA,
            },
        },
    },
    'chatdb': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': MYSQL_DB_CHAT,
        'USER': MYSQL_USER,
        'PASSWORD': MYSQL_PASSWORD,
        'HOST': MYSQL_HOST,
        'PORT': MYSQL_PORT,
        'OPTIONS': {
            'ssl': {
                'ca': MYSQL_CA,
            },
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


LOGIN_URL = '/login/'

# Lark Open Platform credentials
LARK_APP_ID = "cli_a802ed86e438d028"          # Your Lark App ID
LARK_APP_SECRET = "mfbtudMamxM9nKq5tUoh43AJNJT7iJWu"  # Your Lark App Secret

# Bitable App token
LARK_BITABLE_APP_TOKEN_QA = "UbZRbYrtqaDGwMsY9WmlqhAmgGf"  # Your Bitable App Token

# Feishu App ID for IPQC Department
FEISHU_APP_ID = "cli_a83144a175fad00c"
FEISHU_APP_SECRET = "btMHmH3lAqIPQrX5RdIPRcAqn066kCmj"
FEISHU_TABLE_ID  = "tblMZ9PkpgS4cmrq"

# Table IDs for different types of records
LARK_TABLE_IPQC_WORK_INFO = "tblVIUGu6K3bLdJa"                 # For normal work info
LARK_TABLE_BTB_FITMENT_CHECKSHEET = "tbl2t96Qr6eA0jiA"
LARK_TABLE_BUMMY_CHECKSHEET = "tblVei5hahB9MWrV"
LARK_TABLE_DESSEMBLE_CHECKLIST = "tbloHbXh3fhRCskF"
LARK_TABLE_ASSEMBLY_AUDIT = "tbl4ZmtcKC8F6zre"
LARK_TABLE_NC_ISSUE_TRACKING = "tblhQaAEQfwuzWpu"
LARK_TABLE_ESD_COMPLIANCE = "tblZbqVZw4X3HCzA"
LARK_TABLE_DUST_MEASUREMENT = "tblq4hfUqiEnnAYn"
LARK_TABLE_TESTING_FAI = "tblckPOHzkHQGbFN"


AUTH_USER_MODEL = 'accounts.Employee'


DATABASE_ROUTERS = ["chat.db_router.ChatRouter"]

# Channels setup
INSTALLED_APPS += ["channels", "chat"]

ASGI_APPLICATION = "transs_flow.asgi.application"


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20
}
 
# JWT settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}


# CORS settings
CORS_ALLOW_ALL_ORIGINS = True  # Only for development
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # React dev server
    "http://localhost:8080",  # Alternative dev server
    "http://127.0.0.1:3000",
]
 
# Channels settings
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {"hosts": [("127.0.0.1", 6379)]},
    },
}
