# Generated by Django 5.2.7 on 2025-11-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipqc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorqualificationcheck',
            name='scanned_barcode_text',
            field=models.URLField(blank=True, help_text='Auto-filled from barcode scan', max_length=500, null=True, verbose_name='Scanned Job Card URL'),
        ),
    ]
