# Generated by Django 5.2.7 on 2025-10-31 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipqc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipqcdisassemblechecklist',
            name='back_housing',
        ),
        migrations.RemoveField(
            model_name='ipqcdisassemblechecklist',
            name='cam_lens',
        ),
        migrations.RemoveField(
            model_name='ipqcdisassemblechecklist',
            name='camera_sop',
        ),
        migrations.RemoveField(
            model_name='ipqcdisassemblechecklist',
            name='coaxial',
        ),
        migrations.RemoveField(
            model_name='ipqcdisassemblechecklist',
            name='front_acc',
        ),
        migrations.RemoveField(
            model_name='ipqcdisassemblechecklist',
            name='front_housing',
        ),
        migrations.RemoveField(
            model_name='ipqcdisassemblechecklist',
            name='key_sop',
        ),
        migrations.RemoveField(
            model_name='ipqcdisassemblechecklist',
            name='lcd_fabric',
        ),
        migrations.RemoveField(
            model_name='ipqcdisassemblechecklist',
            name='lcd_sop',
        ),
        migrations.RemoveField(
            model_name='ipqcdisassemblechecklist',
            name='led_sop',
        ),
        migrations.RemoveField(
            model_name='ipqcdisassemblechecklist',
            name='mainboard_ok',
        ),
        migrations.RemoveField(
            model_name='ipqcdisassemblechecklist',
            name='mic_sop',
        ),
        migrations.RemoveField(
            model_name='ipqcdisassemblechecklist',
            name='motor_sop',
        ),
        migrations.RemoveField(
            model_name='ipqcdisassemblechecklist',
            name='proof_label',
        ),
        migrations.RemoveField(
            model_name='ipqcdisassemblechecklist',
            name='receiver_sop',
        ),
        migrations.RemoveField(
            model_name='ipqcdisassemblechecklist',
            name='screw_check',
        ),
        migrations.RemoveField(
            model_name='ipqcdisassemblechecklist',
            name='sim_subboard',
        ),
        migrations.RemoveField(
            model_name='ipqcdisassemblechecklist',
            name='speaker_sop',
        ),
        migrations.RemoveField(
            model_name='ipqcdisassemblechecklist',
            name='subboard_sop',
        ),
        migrations.AddField(
            model_name='ipqcdisassemblechecklist',
            name='assembly_overview_photo',
            field=models.ImageField(blank=True, null=True, upload_to='ipqc_disassemble/overview/'),
        ),
        migrations.AddField(
            model_name='ipqcdisassemblechecklist',
            name='back_housing_damage',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'NA')], default='na', max_length=10, verbose_name='Back housing damage/scratch/gap or not'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ipqcdisassemblechecklist',
            name='cam_lens_assembly',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'NA')], default='na', max_length=10, verbose_name='Camera lens assembled correctly'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ipqcdisassemblechecklist',
            name='cam_lens_cleanliness',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'NA')], default='na', max_length=10, verbose_name='Camera lens clean (no dust/fingerprint)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ipqcdisassemblechecklist',
            name='cam_lens_photo',
            field=models.ImageField(blank=True, null=True, upload_to='ipqc_disassemble/camera_lens/'),
        ),
        migrations.AddField(
            model_name='ipqcdisassemblechecklist',
            name='camera_solder',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'NA')], default='na', max_length=10, verbose_name='Camera soldering as per SOP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ipqcdisassemblechecklist',
            name='coaxial_line',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'NA')], default='na', max_length=10, verbose_name='Coaxial line assembled correctly'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ipqcdisassemblechecklist',
            name='color_match_photo',
            field=models.ImageField(blank=True, null=True, upload_to='ipqc_disassemble/color_match/'),
        ),
        migrations.AddField(
            model_name='ipqcdisassemblechecklist',
            name='defect_photo',
            field=models.ImageField(blank=True, null=True, upload_to='ipqc_disassemble/defects/'),
        ),
        migrations.AddField(
            model_name='ipqcdisassemblechecklist',
            name='front_housing_damage',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'NA')], default='na', max_length=10, verbose_name='Front housing damage/scratch/gap or not'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ipqcdisassemblechecklist',
            name='glue_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Measured glue weight (g)'),
        ),
        migrations.AddField(
            model_name='ipqcdisassemblechecklist',
            name='housing_photo',
            field=models.ImageField(blank=True, null=True, upload_to='ipqc_disassemble/housing/'),
        ),
        migrations.AddField(
            model_name='ipqcdisassemblechecklist',
            name='housing_snap_fit',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'NA')], default='na', max_length=10, verbose_name='Front/back housing snap joints fitted properly'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ipqcdisassemblechecklist',
            name='key_alignment',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'NA')], default='na', max_length=10, verbose_name='Keys aligned and no tilt or gap'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ipqcdisassemblechecklist',
            name='key_photo',
            field=models.ImageField(blank=True, null=True, upload_to='ipqc_disassemble/keys/'),
        ),
        migrations.AddField(
            model_name='ipqcdisassemblechecklist',
            name='key_solder',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'NA')], default='na', max_length=10, verbose_name='Key soldering as per SOP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ipqcdisassemblechecklist',
            name='lcd_stick',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'NA')], default='na', max_length=10, verbose_name='LCD sticking/soldering as per SOP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ipqcdisassemblechecklist',
            name='led_solder',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'NA')], default='na', max_length=10, verbose_name='LED soldering as per SOP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ipqcdisassemblechecklist',
            name='mainboard_component_ok',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'NA')], default=',a', max_length=10, verbose_name='Mainboard all components OK'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ipqcdisassemblechecklist',
            name='mic_solder',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'NA')], default='na', max_length=10, verbose_name='Mic soldering as per SOP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ipqcdisassemblechecklist',
            name='motor_solder',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'NA')], default='na', max_length=10, verbose_name='Motor soldering as per SOP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ipqcdisassemblechecklist',
            name='proof_label_photo',
            field=models.ImageField(blank=True, null=True, upload_to='ipqc_disassemble/proof_label/'),
        ),
        migrations.AddField(
            model_name='ipqcdisassemblechecklist',
            name='proof_label_position',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'NA')], default='na', max_length=10, verbose_name='Waterproof label positioned correctly'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ipqcdisassemblechecklist',
            name='receiver_solder',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'NA')], default='na', max_length=10, verbose_name='Receiver soldering as per SOP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ipqcdisassemblechecklist',
            name='screw_loose',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'NA')], default='na', max_length=10, verbose_name='No loose screws'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ipqcdisassemblechecklist',
            name='screw_missing',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'NA')], default='na', max_length=10, verbose_name='All screws present (no missing)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ipqcdisassemblechecklist',
            name='screw_photo',
            field=models.ImageField(blank=True, null=True, upload_to='ipqc_disassemble/screw/'),
        ),
        migrations.AddField(
            model_name='ipqcdisassemblechecklist',
            name='screw_spec',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'NA')], default='na', max_length=10, verbose_name='Screw specification correct'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ipqcdisassemblechecklist',
            name='sim_subboard_solder',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'NA')], default='na', max_length=10, verbose_name='SIM sub-board soldering as per SOP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ipqcdisassemblechecklist',
            name='speaker_solder',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'NA')], default='na', max_length=10, verbose_name='Speaker soldering as per SOP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ipqcdisassemblechecklist',
            name='subboard_solder',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'NA')], default='na', max_length=10, verbose_name='Subboard soldering as per SOP'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='esdcompliancechecklist',
            name='shift',
            field=models.CharField(choices=[('Day', 'Day'), ('Night', 'Night')], max_length=10, verbose_name='Shift'),
        ),
        migrations.AlterField(
            model_name='ipqcdisassemblechecklist',
            name='antenna_fpc',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'NA')], max_length=10, verbose_name='Antenna FPC assembled properly'),
        ),
        migrations.AlterField(
            model_name='ipqcdisassemblechecklist',
            name='antenna_shrapnel',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'NA')], max_length=10, verbose_name='Mainboard antenna shrapnel OK'),
        ),
        migrations.AlterField(
            model_name='ipqcdisassemblechecklist',
            name='cam_glue',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'NA')], max_length=10, verbose_name='Camera back glue not torn off'),
        ),
        migrations.AlterField(
            model_name='ipqcdisassemblechecklist',
            name='color_match',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'NA')], max_length=10, verbose_name='Color matches reference or not'),
        ),
        migrations.AlterField(
            model_name='ipqcdisassemblechecklist',
            name='conductive_fabric',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'NA')], max_length=10, verbose_name='Conductive fabric positioned as per SOP'),
        ),
        migrations.AlterField(
            model_name='ipqcdisassemblechecklist',
            name='defect_cause',
            field=models.TextField(blank=True, null=True, verbose_name='Defect Cause Analysis / Remark'),
        ),
        migrations.AlterField(
            model_name='ipqcdisassemblechecklist',
            name='foam_stick',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'NA')], max_length=10, verbose_name='Foam stick positioned correctly'),
        ),
        migrations.AlterField(
            model_name='ipqcdisassemblechecklist',
            name='glue_location',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'NA')], max_length=10, verbose_name='Thermal/battery/deco glue on correct location'),
        ),
        migrations.AlterField(
            model_name='ipqcdisassemblechecklist',
            name='ins_paste_cover',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'NA')], max_length=10, verbose_name='Insulation paste fully covers all pins'),
        ),
        migrations.AlterField(
            model_name='ipqcdisassemblechecklist',
            name='insulation_paste',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'NA')], max_length=10, verbose_name='Insulation paste positioned correctly'),
        ),
        migrations.AlterField(
            model_name='ipqcdisassemblechecklist',
            name='jig_fixture_test',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'NA')], max_length=10, verbose_name='Jig/fixture impression test done & verified glue activation'),
        ),
        migrations.AlterField(
            model_name='ipqcdisassemblechecklist',
            name='key_feel',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'NA')], max_length=10, verbose_name='Key hand feeling OK'),
        ),
        migrations.AlterField(
            model_name='ipqcdisassemblechecklist',
            name='key_fpc_solder',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'NA')], max_length=10, verbose_name='Key FPC soldering OK'),
        ),
        migrations.AlterField(
            model_name='ipqcdisassemblechecklist',
            name='keypad_defect',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'NA')], max_length=10, verbose_name='Keypad FPC has no burn/indentation'),
        ),
        migrations.AlterField(
            model_name='ipqcdisassemblechecklist',
            name='lcd_fpc_defect',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'NA')], max_length=10, verbose_name='LCD FPC indentation/scald or not'),
        ),
        migrations.AlterField(
            model_name='ipqcdisassemblechecklist',
            name='led_position',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'NA')], max_length=10, verbose_name='LED centered correctly'),
        ),
        migrations.AlterField(
            model_name='ipqcdisassemblechecklist',
            name='solder_splash',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'NA')], max_length=10, verbose_name='No solder splash or foreign material inside device'),
        ),
        migrations.AlterField(
            model_name='ipqcdisassemblechecklist',
            name='tp_fpc_defect',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'NA')], max_length=10, verbose_name='TP FPC indentation/scald or not'),
        ),
        migrations.AlterField(
            model_name='ipqcdisassemblechecklist',
            name='tp_sop',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'NA')], max_length=10, verbose_name='Touch Panel assembled as per SOP'),
        ),
    ]
