# Generated by Django 5.2.7 on 2025-11-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipqc', '0002_operatorqualificationcheck_scanned_barcode_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorqualificationcheck',
            name='feishu_record_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Feishu Record Data'),
        ),
    ]
