# Generated by Django 5.2.7 on 2025-10-31 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipqc', '0002_remove_ipqcdisassemblechecklist_back_housing_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipqcdisassemblechecklist',
            old_name='glue_weight',
            new_name='glue_weight_1',
        ),
        migrations.AddField(
            model_name='ipqcdisassemblechecklist',
            name='glue_weight_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Measured glue weight (g)'),
        ),
        migrations.AddField(
            model_name='ipqcdisassemblechecklist',
            name='glue_weight_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Measured glue weight (g)'),
        ),
    ]
