# Generated by Django 5.2.7 on 2025-11-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipqc", "0003_operatorqualificationcheck_feishu_record_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="operatorqualificationcheck",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Operator Qualification Procedure",
                "verbose_name_plural": "Operator Qualification Procedures",
            },
        ),
        migrations.RemoveField(
            model_name="ipqcassemblyaudit",
            name="man_btb_mon",
        ),
        migrations.RemoveField(
            model_name="ipqcassemblyaudit",
            name="man_job_card",
        ),
        migrations.AddField(
            model_name="ipqcassemblyaudit",
            name="mach_sholdering_temp",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "NA")],
                max_length=200,
                null=True,
                verbose_name="Check soldering temp per SOP.",
            ),
        ),
        migrations.AlterField(
            model_name="assdummytest",
            name="cause",
            field=models.TextField(
                blank=True, null=True, verbose_name="Cause of Failure"
            ),
        ),
        migrations.AlterField(
            model_name="assdummytest",
            name="ll_confirm",
            field=models.TextField(verbose_name="Line Leader Confirm"),
        ),
        migrations.AlterField(
            model_name="assdummytest",
            name="measure",
            field=models.TextField(
                blank=True, null=True, verbose_name="Corrective Measure"
            ),
        ),
        migrations.AlterField(
            model_name="assdummytest",
            name="operator_id",
            field=models.CharField(max_length=50, verbose_name="Operator ID"),
        ),
        migrations.AlterField(
            model_name="assdummytest",
            name="operator_name",
            field=models.CharField(max_length=100, verbose_name="Operator Name"),
        ),
        migrations.AlterField(
            model_name="assdummytest",
            name="remark",
            field=models.TextField(blank=True, null=True, verbose_name="Remark"),
        ),
        migrations.AlterField(
            model_name="assdummytest",
            name="result",
            field=models.CharField(
                choices=[("Pass", "Pass"), ("Fail", "Fail"), ("NA", "NA")],
                max_length=10,
                verbose_name="Test Result",
            ),
        ),
        migrations.AlterField(
            model_name="assdummytest",
            name="test_item",
            field=models.CharField(max_length=200, verbose_name="Test Item"),
        ),
        migrations.AlterField(
            model_name="assdummytest",
            name="test_stage",
            field=models.CharField(max_length=100, verbose_name="Test Stage"),
        ),
        migrations.AlterField(
            model_name="ipqcassemblyaudit",
            name="auto_screw_sample",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "NA")],
                max_length=200,
                null=True,
                verbose_name="Hourly check 4 auto-screw samples before Seg-1/RQC; ensure no dent or mark.",
            ),
        ),
        migrations.AlterField(
            model_name="ipqcassemblyaudit",
            name="defect_monitor",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "NA")],
                max_length=200,
                null=True,
                verbose_name="Verify key station defect records and ensure defect rate within limits.",
            ),
        ),
        migrations.AlterField(
            model_name="ipqcassemblyaudit",
            name="env_5s",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "NA")],
                max_length=200,
                null=True,
                verbose_name="Verify 5S compliance (Sort, Set, Shine, Standardize, Sustain) in assembly area.",
            ),
        ),
        migrations.AlterField(
            model_name="ipqcassemblyaudit",
            name="env_prod_monitor",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "NA")],
                max_length=200,
                null=True,
                verbose_name="Check temp (16–28°C), humidity (45–75%), and environment twice per shift per spec.",
            ),
        ),
        migrations.AlterField(
            model_name="ipqcassemblyaudit",
            name="fai_check",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "NA")],
                max_length=200,
                null=True,
                verbose_name="Check FAI: function, appearance, material per BOM/SOP, SW version, labels, and tests.",
            ),
        ),
        migrations.AlterField(
            model_name="ipqcassemblyaudit",
            name="mach_auto_screw",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "NA")],
                max_length=200,
                null=True,
                verbose_name="Auto screw: teaching per SOP; no loose/missing screws (5 pcs/hr).",
            ),
        ),
        migrations.AlterField(
            model_name="ipqcassemblyaudit",
            name="mach_cleanroom_eq",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "NA")],
                max_length=200,
                null=True,
                verbose_name="Check cleanroom equipment and checklist compliance.",
            ),
        ),
        migrations.AlterField(
            model_name="ipqcassemblyaudit",
            name="mach_current_test",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "NA")],
                max_length=200,
                null=True,
                verbose_name="Current test parameters match standard; limits OK.",
            ),
        ),
        migrations.AlterField(
            model_name="ipqcassemblyaudit",
            name="mach_epa_check",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "NA")],
                max_length=200,
                null=True,
                verbose_name="Verify EPA compliance—antistatic gear and proper grounding.",
            ),
        ),
        migrations.AlterField(
            model_name="ipqcassemblyaudit",
            name="mach_eq_move_notify",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "NA")],
                max_length=200,
                null=True,
                verbose_name="Report any jig/equipment movement or change to PQE.",
            ),
        ),
        migrations.AlterField(
            model_name="ipqcassemblyaudit",
            name="mach_feeler_gauge",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "NA")],
                max_length=200,
                null=True,
                verbose_name="Check feeler gauge twice per shift.",
            ),
        ),
        migrations.AlterField(
            model_name="ipqcassemblyaudit",
            name="mach_fixture_clean",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "NA")],
                max_length=200,
                null=True,
                verbose_name="Fixtures/machines clean and free from dirt; verify 5 samples visually.",
            ),
        ),
        migrations.AlterField(
            model_name="ipqcassemblyaudit",
            name="mach_glue_params",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "NA")],
                max_length=200,
                null=True,
                verbose_name="Check glue parameters and alignment per SOP.",
            ),
        ),
        migrations.AlterField(
            model_name="ipqcassemblyaudit",
            name="mach_hot_cold_press",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "NA")],
                max_length=200,
                null=True,
                verbose_name="Verify hot/cold press parameters.",
            ),
        ),
        migrations.AlterField(
            model_name="ipqcassemblyaudit",
            name="mach_ion_fan",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "NA")],
                max_length=200,
                null=True,
                verbose_name="Ion fan facing work area, 30–40 cm distance.",
            ),
        ),
        migrations.AlterField(
            model_name="ipqcassemblyaudit",
            name="mach_jig_label",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "NA")],
                max_length=200,
                null=True,
                verbose_name="Jig label matches model; maintenance label valid.",
            ),
        ),
        migrations.AlterField(
            model_name="ipqcassemblyaudit",
            name="mach_light",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "NA")],
                max_length=200,
                null=True,
                verbose_name="Ensure CTQ light level 800–1200 Lux.",
            ),
        ),
        migrations.AlterField(
            model_name="ipqcassemblyaudit",
            name="mach_pal_qr",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "NA")],
                max_length=200,
                null=True,
                verbose_name="PAL: Verify QR print, SN match, no duplicates.",
            ),
        ),
        migrations.AlterField(
            model_name="ipqcassemblyaudit",
            name="mach_press_params",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "NA")],
                max_length=200,
                null=True,
                verbose_name="Pressing pressure/time within limit.",
            ),
        ),
        migrations.AlterField(
            model_name="ipqcassemblyaudit",
            name="mach_rti_check",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "NA")],
                max_length=200,
                null=True,
                verbose_name="RTI: Verify QR, SN, and software per BOM.",
            ),
        ),
        migrations.AlterField(
            model_name="ipqcassemblyaudit",
            name="mach_screw_torque",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "NA")],
                max_length=200,
                null=True,
                verbose_name="Check screwdriver torque (<0.9 kgf/cm²) per SOP.",
            ),
        ),
        migrations.AlterField(
            model_name="ipqcassemblyaudit",
            name="mach_teflon",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "NA")],
                max_length=200,
                null=True,
                verbose_name="Teflon on fixture not raised, creased, or damaged.",
            ),
        ),
        migrations.AlterField(
            model_name="ipqcassemblyaudit",
            name="mat_battery_issue",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "NA")],
                max_length=200,
                null=True,
                verbose_name="If battery leaks, smokes, or burns—inform PQE immediately.",
            ),
        ),
        migrations.AlterField(
            model_name="ipqcassemblyaudit",
            name="mat_improved_monitor",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "NA")],
                max_length=200,
                null=True,
                verbose_name="Monitor use of improved/deviation materials per document and inform PQE.",
            ),
        ),
        migrations.AlterField(
            model_name="ipqcassemblyaudit",
            name="mat_ipa_check",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "NA")],
                max_length=200,
                null=True,
                verbose_name="Verify IPA use per SOP (0.5 ml for battery/PCBA); container labeled.",
            ),
        ),
        migrations.AlterField(
            model_name="ipqcassemblyaudit",
            name="mat_key_check",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "NA")],
                max_length=200,
                null=True,
                verbose_name="Check key materials every 2 hrs (Mainboard, LCM, FPC, etc.); all others once per shift.",
            ),
        ),
        migrations.AlterField(
            model_name="ipqcassemblyaudit",
            name="mat_result_check",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "NA")],
                max_length=200,
                null=True,
                verbose_name="Check assembly results—no shift, lift, missing or loose screws (5 pcs/sample).",
            ),
        ),
        migrations.AlterField(
            model_name="ipqcassemblyaudit",
            name="mat_special_stop",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "NA")],
                max_length=200,
                null=True,
                verbose_name="Verify stopped/suspended materials (date code, batch, supplier) are not in use.",
            ),
        ),
        migrations.AlterField(
            model_name="ipqcassemblyaudit",
            name="mat_thermal_gel",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "NA")],
                max_length=200,
                null=True,
                verbose_name="Check thermal gel weight, position, and route per model/SOP.",
            ),
        ),
        migrations.AlterField(
            model_name="ipqcassemblyaudit",
            name="mat_verification",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "NA")],
                max_length=200,
                null=True,
                verbose_name="Verify materials match BOM/SOP and correct quantity/location used.",
            ),
        ),
        migrations.AlterField(
            model_name="ipqcassemblyaudit",
            name="meth_battery_fix",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "NA")],
                max_length=200,
                null=True,
                verbose_name="Check inbuilt battery fixed properly before cover installation.",
            ),
        ),
        migrations.AlterField(
            model_name="ipqcassemblyaudit",
            name="meth_defective_feedback",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "NA")],
                max_length=200,
                null=True,
                verbose_name="Report defects to PQE; supervise segregation and rework as required.",
            ),
        ),
        migrations.AlterField(
            model_name="ipqcassemblyaudit",
            name="meth_distance_sensor",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "NA")],
                max_length=200,
                null=True,
                verbose_name="Check distance sensor jig height = 2.25 cm ± tolerance.",
            ),
        ),
        migrations.AlterField(
            model_name="ipqcassemblyaudit",
            name="meth_dummy_conduct",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "NA")],
                max_length=200,
                null=True,
                verbose_name="Conduct dummy checks for key stages, new changes, or top defects daily.",
            ),
        ),
        migrations.AlterField(
            model_name="ipqcassemblyaudit",
            name="meth_guideline_doc",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "NA")],
                max_length=200,
                null=True,
                verbose_name="Ensure valid SOP/OPL displayed; remove expired or unused documents.",
            ),
        ),
        migrations.AlterField(
            model_name="ipqcassemblyaudit",
            name="meth_line_change",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "NA")],
                max_length=200,
                null=True,
                verbose_name="For line/model change, verify all materials within 3 hrs; clear old stock.",
            ),
        ),
        migrations.AlterField(
            model_name="ipqcassemblyaudit",
            name="meth_line_record",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "NA")],
                max_length=200,
                null=True,
                verbose_name="Verify line reports/checksheets are properly filled and equipment OK.",
            ),
        ),
        migrations.AlterField(
            model_name="ipqcassemblyaudit",
            name="meth_material_handling",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "NA")],
                max_length=200,
                null=True,
                verbose_name="Verify material handling, storage, and stacking per document.",
            ),
        ),
        migrations.AlterField(
            model_name="ipqcassemblyaudit",
            name="meth_no_self_repair",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "NA")],
                max_length=200,
                null=True,
                verbose_name="No self-repair or fixture modification by production staff.",
            ),
        ),
        migrations.AlterField(
            model_name="ipqcassemblyaudit",
            name="meth_operation_doc",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "NA")],
                max_length=200,
                null=True,
                verbose_name="Follow only approved documents; no verbal or unauthorized changes.",
            ),
        ),
        migrations.AlterField(
            model_name="ipqcassemblyaudit",
            name="meth_rear_camera",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "NA")],
                max_length=200,
                null=True,
                verbose_name="Check rear camera seal/cushion after battery cover and TRC repair.",
            ),
        ),
        migrations.AlterField(
            model_name="ipqcassemblyaudit",
            name="meth_sop_seq",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "NA")],
                max_length=200,
                null=True,
                verbose_name="Verify SOP sequence, process completeness, and tool availability.",
            ),
        ),
        migrations.AlterField(
            model_name="ipqcassemblyaudit",
            name="meth_trail_run",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "NA")],
                max_length=200,
                null=True,
                verbose_name="During trial/new line start, monitor 4M1E, fill readiness sheet, and check 5 pcs.",
            ),
        ),
        migrations.AlterField(
            model_name="ipqcassemblyaudit",
            name="spot_check",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "NA")],
                max_length=200,
                null=True,
                verbose_name="Spot check boards/semi-finished units to confirm MES entry (Online/TRC).",
            ),
        ),
        migrations.AlterField(
            model_name="ipqcassemblyaudit",
            name="trc_flow_chart",
            field=models.CharField(
                blank=True,
                choices=[("OK", "OK"), ("NOT_OK", "Not OK"), ("NA", "NA")],
                max_length=200,
                null=True,
                verbose_name="Ensure flow chart available; verify MES defect entry and 5S at TRC station.",
            ),
        ),
        migrations.AlterField(
            model_name="operatorqualificationcheck",
            name="key_station_name",
            field=models.TextField(verbose_name="Select/Write the key station Name"),
        ),
    ]
