# Generated by Django 5.2.7 on 2025-11-20 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipqc', '0004_alter_operatorqualificationcheck_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assdummytest',
            name='work_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipqc.ipqcworkinfo'),
        ),
        migrations.AddField(
            model_name='btbfitmentchecksheet',
            name='work_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipqc.ipqcworkinfo'),
        ),
        migrations.AddField(
            model_name='dustcountcheck',
            name='work_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipqc.ipqcworkinfo'),
        ),
        migrations.AddField(
            model_name='esdcompliancechecklist',
            name='work_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipqc.ipqcworkinfo'),
        ),
        migrations.AddField(
            model_name='ipqcassemblyaudit',
            name='work_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipqc.ipqcworkinfo'),
        ),
        migrations.AddField(
            model_name='ipqcdisassemblechecklist',
            name='work_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipqc.ipqcworkinfo'),
        ),
        migrations.AddField(
            model_name='ncissuetracking',
            name='work_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipqc.ipqcworkinfo'),
        ),
        migrations.AddField(
            model_name='operatorqualificationcheck',
            name='work_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipqc.ipqcworkinfo'),
        ),
        migrations.AddField(
            model_name='testingfirstarticleinspection',
            name='work_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipqc.ipqcworkinfo'),
        ),
    ]
