# Generated by Django 5.2.7 on 2025-11-01 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipqc', '0004_alter_ipqcdisassemblechecklist_glue_weight_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testingfirstarticleinspection',
            name='form_no',
        ),
        migrations.RemoveField(
            model_name='testingfirstarticleinspection',
            name='line_group',
        ),
        migrations.RemoveField(
            model_name='testingfirstarticleinspection',
            name='model_color',
        ),
        migrations.RemoveField(
            model_name='testingfirstarticleinspection',
            name='model_description',
        ),
        migrations.RemoveField(
            model_name='testingfirstarticleinspection',
            name='work_info',
        ),
        migrations.AddField(
            model_name='testingfirstarticleinspection',
            name='color',
            field=models.CharField(default='na', max_length=50, verbose_name='Color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testingfirstarticleinspection',
            name='emp_id',
            field=models.CharField(default='na', max_length=20, verbose_name='Employee ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testingfirstarticleinspection',
            name='group',
            field=models.CharField(default='na', max_length=100, verbose_name='Group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testingfirstarticleinspection',
            name='line',
            field=models.CharField(default='na', max_length=100, verbose_name='Line'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testingfirstarticleinspection',
            name='model',
            field=models.CharField(default='na', max_length=100, verbose_name='Model'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testingfirstarticleinspection',
            name='name',
            field=models.CharField(default='na', max_length=100, verbose_name='Employee Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testingfirstarticleinspection',
            name='shift',
            field=models.CharField(default='na', max_length=10, verbose_name='Shift'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
