# Generated by Django 5.2.7 on 2025-11-04 04:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipqc', '0006_remove_testingfirstarticleinspection_assembly_battery_check_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testingfirstarticleinspection',
            name='public_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='testingfirstarticleinspection',
            name='public_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testingfirstarticleinspection',
            name='qe_confirm_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='QE Confirm Name'),
        ),
    ]
