# Generated by Django 5.2.7 on 2025-11-04 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipqc', '0007_testingfirstarticleinspection_public_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='qe_confirm_status',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Not Approved', 'Not Approved'), ('NA', 'NA')], max_length=100, null=True, verbose_name='QE Confirm Status'),
        ),
    ]
