# Generated by Django 5.2.7 on 2025-11-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipqc', '0008_alter_testingfirstarticleinspection_qe_confirm_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='gravity_sensor_test',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'NA')], max_length=100, verbose_name='Gravity sensor function is normal'),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='label_check',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'NA')], max_length=20, verbose_name="check with BOM list ,if there's missing, pasted in wrong place etc"),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='light_distance_sensor_test',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'NA')], max_length=100, verbose_name='Light sensor, distance sensor function is normal'),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='memory_inbuilt_check',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'NA')], max_length=20, verbose_name='Result'),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='reliability_result',
            field=models.CharField(choices=[('QUALIFIED', 'Qualified'), ('UNQUALIFIED', 'Unqualified'), ('CONDITIONAL_ACC', 'Conditional Acceptance')], max_length=30, verbose_name='Reliability Test Result'),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='visual_functional_result',
            field=models.CharField(choices=[('QUALIFIED', 'Qualified'), ('UNQUALIFIED', 'Unqualified'), ('CONDITIONAL_ACC', 'Conditional Acceptance')], max_length=30, verbose_name='Visual & Functional Test Result'),
        ),
        migrations.AlterModelTable(
            name='testingfirstarticleinspection',
            table='ipqc_testing_first_article_inspection',
        ),
    ]
