# Generated by Django 5.2.7 on 2025-11-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipqc', '0009_alter_testingfirstarticleinspection_gravity_sensor_test_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='boot_time_test_evidence',
            field=models.ImageField(blank=True, null=True, upload_to='fai/function/', verbose_name='Evidence File'),
        ),
    ]
