# Generated by Django 5.2.7 on 2025-11-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipqc', '0010_alter_testingfirstarticleinspection_boot_time_test_evidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='assembly_battery_check',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'Not Applicable')], max_length=100, verbose_name='Assembly of battery cover/surface shell/bottom case has no segment difference and is not too tight or loose'),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='bluetooth_test',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'Not Applicable')], max_length=100, verbose_name='Bluetooth Function Test'),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='boot_time_test',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'Not Applicable')], max_length=100, verbose_name='Boot Bright Screen Time Test (<2s)'),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='boot_time_test_evidence',
            field=models.ImageField(blank=True, null=True, upload_to='fai/function/', verbose_name='Boot time evidence image'),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='buttons_keys_test',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'Not Applicable')], max_length=100, verbose_name='Buttons/Side Keys Feel Test'),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='calling_test',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'Not Applicable')], max_length=100, verbose_name='Calling Test (with/without earphone)'),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='camera_dark_test',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'Not Applicable')], max_length=100, verbose_name='Camera in Dark Condition Test'),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='camera_flash_test',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'Not Applicable')], max_length=100, verbose_name='Photo flash is normal'),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='camera_long_distance_check',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'Not Applicable')], max_length=100, verbose_name='Long Distance (8W:50cm; 30W:60cm; 200W FF:3m; 500W+:3–5m)'),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='camera_photo_test',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'Not Applicable')], max_length=100, verbose_name='Front/Rear Camera Photo Test'),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='charge_15min_test',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'Not Applicable')], max_length=100, verbose_name='Actual 15min Charging Test'),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='coumpling_rf_test',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'Not Applicable')], max_length=100, verbose_name='“GSM900/1800 power & interference test (CMD55, call/touch/earphone check)'),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='factory_reset_call_noise_test',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'Not Applicable')], max_length=100, verbose_name='Post- factory reset check Call interface key noise and sound quality test'),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='factory_reset_fn_test',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'Not Applicable')], max_length=100, verbose_name='Post- factory reset function check – photo, video, BT, download'),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='factory_reset_test',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'Not Applicable')], max_length=100, verbose_name="Test model, select 'factory reset', input '234', click 'ENTER', reset handset and do the visual inspection."),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='flashlight_test',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'Not Applicable')], max_length=100, verbose_name='Flashlight/Induction Lamp Test'),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='fm_play_test',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'Not Applicable')], max_length=100, verbose_name='Can search & play FM normally'),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='focus_test',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'Not Applicable')], max_length=100, verbose_name='Auto-focus clarity test at ≥10 cm distance'),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='front_back_cam_test',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'Not Applicable')], max_length=100, verbose_name='Front/Back camera photo test (10 shots each)'),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='gravity_sensor_test',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'Not Applicable')], max_length=100, verbose_name='Gravity sensor function is normal'),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='hall_fn_test',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'Not Applicable')], max_length=100, verbose_name='Hall function is normal'),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='high_temp_boot_check',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'Not Applicable')], max_length=100, verbose_name='Boot-up test (4× total, 2× with & 2× without battery; check display after high-temp)'),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='high_temp_call_test',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'Not Applicable')], max_length=100, verbose_name='Call function test (dial 198, check connection, receiver & mic sound quality)'),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='high_temp_camera_test',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'Not Applicable')], max_length=100, verbose_name='High Temp Camera Test: Camera function test (front/rear preview, capture, flash, album browse & delete)'),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='high_temp_charging_test',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'Not Applicable')], max_length=100, verbose_name='Post-chamber charging test (verify charging function & battery display)'),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='high_temp_engi_mode_test',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'Not Applicable')], max_length=100, verbose_name=' The engineering model test content completely'),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='high_temp_simul_test',
            field=models.TextField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'Not Applicable')], max_length=100, verbose_name='High temperature simulation test: Half-day batches tested by IPQC; issues retested and reported to PQE, who alerts departments and stops the line if needed'),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='highlight_defect_check',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'Not Applicable')], max_length=100, verbose_name='High-Light (800–1200Lux) – Check White Screen, Exposure, Distortion'),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='init_settings_test',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'Not Applicable')], max_length=100, verbose_name='Initialization Settings & Function Test'),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='label_check',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'Not Applicable')], max_length=20, verbose_name="check with BOM list ,if there's missing, pasted in wrong place etc"),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='label_position_check',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'Not Applicable')], max_length=100, verbose_name='Label position should meet the requirements of the SOP '),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='light_distance_sensor_test',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'Not Applicable')], max_length=100, verbose_name='Light sensor, distance sensor function is normal'),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='logo_check',
            field=models.TextField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'Not Applicable')], max_length=100, verbose_name='Logo Check is right or not'),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='mac_add_test',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'Not Applicable')], max_length=100, verbose_name='Check MAC address'),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='memory_inbuilt_check',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'Not Applicable')], max_length=20, verbose_name='Result'),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='mode_switch_test',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'Not Applicable')], max_length=100, verbose_name='Different mode can be switch normally'),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='multimedia_play_test',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'Not Applicable')], max_length=100, verbose_name='Can play MP3, MP4 normally'),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='net_color_check',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'Not Applicable')], max_length=100, verbose_name='Check if there is net cover with the handset and its colour is consistent'),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='order_confirm_check',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'Not Applicable')], max_length=20, verbose_name='Confirm if inspection information is consistent with actual shipment requirements'),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='otg_fn_test',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'Not Applicable')], max_length=100, verbose_name='OTG function is normal'),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='power_consumption_test',
            field=models.TextField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'Not Applicable')], max_length=100, verbose_name='Power Consumption Test (standby, startup, BT, vibration, backlight, MP3/MP4 with dual SIM)'),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='qe_confirm_status',
            field=models.CharField(blank=True, choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PENDING', 'Pending')], max_length=100, null=True, verbose_name='QE Confirm Status'),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='qr_scan_test',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'Not Applicable')], max_length=100, verbose_name='QR code test, Scane the QR code and check should be same with device SN'),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='ram_rom_cap_test',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'Not Applicable')], max_length=100, verbose_name='check if T card capacity，RAM capacity， ROM capacity are normal'),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='reliability_result',
            field=models.CharField(choices=[('MEET_REQ', 'Meet Requirement'), ('QUALIFIED', 'Qualified'), ('UNQUALIFIED', 'Unqualified'), ('CONDITIONAL_ACC', 'Conditional Acceptance')], max_length=30, verbose_name='Reliability Test Result'),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='sar_value_test',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'Not Applicable')], max_length=100, verbose_name='*SAR value check via #07# and device manual'),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='screw_check',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'Not Applicable')], max_length=100, verbose_name="Check if there's screw missing or untigtened"),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='shaking_screen_test',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'Not Applicable')], max_length=100, verbose_name='Shaking screen function is normal'),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='slight_drop_test',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'Not Applicable')], max_length=100, verbose_name='Slight Drop Test (7 cm, 6 sides × 20 drops = 120; no cover loss, call/power stable, no paint damage)'),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='slight_touch_test',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'Not Applicable')], max_length=100, verbose_name='Charging function & USB port stability test (touch 5×, no charge breaks)'),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='taping_fn_test',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'Not Applicable')], max_length=100, verbose_name='Taping function is normal'),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='tcard_sim_plug_test',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'Not Applicable')], max_length=100, verbose_name='T-Card/SIM Plug/Pull Test (10 cycles)'),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='touch_in_dev_opt_test',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'Not Applicable')], max_length=100, verbose_name='Touch test in Developer options'),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='touch_screen_pen_test',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'Not Applicable')], max_length=100, verbose_name='Touch Screen Pen/Drift Test'),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='tp_with_charge_test',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'Not Applicable')], max_length=100, verbose_name='No TP drift or display abnormality during charger on/off.'),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='tp_with_key_check',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'Not Applicable')], max_length=100, verbose_name='Press the top, bottom, left, right, receiver, menu key of TP, check if the TP is defective'),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='tv_fn_test',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'Not Applicable')], max_length=100, verbose_name='TV function is normal'),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='visual_functional_result',
            field=models.CharField(choices=[('MEET_REQ', 'Meet Requirement'), ('QUALIFIED', 'Qualified'), ('UNQUALIFIED', 'Unqualified'), ('CONDITIONAL_ACC', 'Conditional Acceptance')], max_length=30, verbose_name='Visual & Functional Test Result'),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='visual_inspection_handset',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'Not Applicable')], max_length=100, verbose_name='Visual Handset Appearance Check'),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='wifi_test',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'Not Applicable')], max_length=100, verbose_name='WIFI function is normal'),
        ),
    ]
