# Generated by Django 5.2.7 on 2025-11-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipqc', '0011_alter_testingfirstarticleinspection_assembly_battery_check_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='high_temp_simul_test',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'Not Applicable')], max_length=100, verbose_name='High temperature simulation test: Half-day batches tested by IPQC; issues retested and reported to PQE, who alerts departments and stops the line if needed'),
        ),
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='power_consumption_test',
            field=models.CharField(choices=[('OK', 'OK'), ('Not OK', 'Not OK'), ('NA', 'Not Applicable')], max_length=100, verbose_name='Power Consumption Test (standby, startup, BT, vibration, backlight, MP3/MP4 with dual SIM)'),
        ),
    ]
