# Generated by Django 5.2.7 on 2025-11-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipqc', '0012_alter_testingfirstarticleinspection_high_temp_simul_test_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='imei_number',
            field=models.IntegerField(max_length=100, verbose_name='IMEI Number'),
        ),
    ]
