# Generated by Django 5.2.7 on 2025-11-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipqc', '0014_alter_testingfirstarticleinspection_imei_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testingfirstarticleinspection',
            name='imei_number',
            field=models.CharField(max_length=100, verbose_name='IMEI Number'),
        ),
    ]
