# Generated by Django 5.2.7 on 2025-11-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipqc', '0018_alter_testingfirstarticleinspection_imei_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testingfirstarticleinspection',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks'),
        ),
    ]
